### ISSUE TITLE
Unit test for parseFromAnchor function is dodgy 

### ISSUE THREAD

**Issue by vbence86** [metal/metal-uri#13]
##### Declaimer 
This module has been linked to Travis CI in ```travis``` branch (https://github.com/metal/metal-uri/tree/travis), but the test apparently fails against certain Saucelabs browsers.

##### Travis Output
https://travis-ci.org/metal/metal-uri/builds/258612453

##### Recurring issues
- ```parseFromAnchor should throw a TypeError exception on invalid URLs FAILED```
- ```parse should throw a TypeError exception on invalid URLs FAILED```

While looking into this issue we came across that the function responsable for URL validation is a bit dodgy and fails in its purpose. It creates an ```<a>``` instance and sets its ```href``` attribute against the given URL that is believed to be invalid. The specified browsers taking part in the test  nevertheless automatically generate a valid URL out of this invalid one by invoking a transparent native code as soon as the ```<a>``` instance's ```href``` attribute is altered.  

##### Proposal
Please double check whether or not the existence of this test provides any value to the building process.

The dodgy code snippet copied from ```parseFromAnchor.js```

```javascript
	var link = document.createElement('a');
	link.href = opt_uri;

	if(link.protocol === ':' || !/:/.test(link.href)) {
		throw new TypeError(`${opt_uri} is not a valid URL`);
	}
```

**Comment by jbalsas** [comment]
Hey @vbence86, please see https://github.com/metal/metal-uri/issues/11 for the rationale behind the `TypeError` exception and https://github.com/metal/metal-uri/pull/12 for the PR that went in. 

Maybe we missed something?

**Comment by vbence86** [comment]
@jbalsas Thanks for shading some light on this the goal of the test is now clear. 
According to the **WHATWG living standard** of URI the relevant definition is the following:

> If port is greater than 2^16 − 1, validation error, return failure.

I suggest to change the description of the test case at first. 
I've created a PR for that - https://github.com/metal/metal-uri/pull/16 

The reason why the tests are failing are that various browsers didn't parse the given URL according to this expectation and the `link.protocol` doesn't equal to `:` character.

**Comment by vbence86** [comment]
To follow this up, I've created a Pull Request that addresses the mentioned issue. 
https://github.com/metal/metal-uri/pull/17

**Comment by Robert-Frampton** [comment]
Hey @vbence86 

I'm assuming #18 closes this issue?

**Comment by vbence86** [comment]
@Robert-Frampton Indeed, I merely forgot to update that issue after #18 had been merged.
