### ISSUE TITLE
Throws an exception in ReactNative 16

### ISSUE THREAD

**Issue by ipeychev** [metal/metal-uri#19]
In ReactNative 16 [this check](https://github.com/metal/metal-uri/blob/9c2b9f8197e9530e7054b5d02da3c3a089b34103/src/parse.js#L12) fails since `URL` is an object, but `URL.length` is 0.

Question: What if we drop the current implementation which uses URL or parsing via `a` element and replace it with a specially prepared module for that purpose, which has small footprint and does not use any native objects? This could be [url-parse](https://www.npmjs.com/package/url-parse) module.

**Comment by eduardolundgren** [comment]
How was that working before?

**Comment by ipeychev** [comment]
In ReactNative 15 URL was the native object as in the browser. In ReactNative 16 it is something else - their [own class](https://github.com/facebook/react-native/blob/91372e8f9aafcad2b5594175b1a3ce6f9c8f3b8e/Libraries/Blob/URL.js).

I opened an issue for them [here](https://github.com/facebook/react-native/issues/16434) to see what will they say too.

**Comment by jbalsas** [comment]
Can we wait until they let us know? We could simply adapt the native check if needed...

On the other hand, it is true that the native+fallback implementation we have is in fact more fragile and browser-dependent than we'd like to. Considering all the fixes we already had to apply for `metal-uri` to behave consistently across browsers, it might make sense to just go with a full-fledged `urlparser`.

**Comment by ipeychev** [comment]
Hey Chema,

I think we have to go ahead and change the implementation here for at least those reasons:
1. Even if they answer us on time, which I doubt, it will take time to fix it and release a new version. Meanwhile, WeDeploy's API JS is unusable in ReactNative 16, probably in ReactVR, haven't tested in Electron, hope it works at least there.
2. The current implementation is indeed fragile. Those are actually two implementations - Node and browsers and as I see a few patches were applied to keep the browser one in a good shape.
3. Even with those two implementations, it doesn't work in all environments.

Eduardo is also OK if we change it and use only one implementation and we may start with [url-parse](https://www.npmjs.com/package/url-parse). Would it be possible for someone from Spain to apply this really quickly?

@jbalsas

**Comment by jbalsas** [comment]
Hey @ipeychev, we can definitely take a look, but I'm not so sure about the timeframe. 

@vbence86 is finishing the [update of AlloyEditor to React16](https://github.com/liferay/alloy-editor/issues/770), so he might be able to get to this as soon as he's done with it. @Robert-Frampton should be coming back from LSNA soon as well. It would take at least a couple of days, but we can prioritize this.

Just to clarify, are we talking about simply consuming [url-parse](https://www.npmjs.com/package/url-parse) or maintaining our own implementation?

**Comment by ipeychev** [comment]
Hey @jbalsas ,

I would say let's go for now with [url-parse](https://www.npmjs.com/package/url-parse) (or with something similar, I don't mind). I don't see a strong reason for our own implementation at this moment.

**Comment by eduardolundgren** [comment]
@jbalsas The `url-parser` module will replace the native `URL` and Node.js parsing. The rest of `metal-uri` will stay intact. This change, should not cause any changes in the test cases.

**Comment by jbalsas** [comment]
Yeah, we're on it, we'll get started as soon as we finish with the AlloyEditor React16 story I mentioned... unless @Robert-Frampton beats us to it 😉

**Comment by Robert-Frampton** [comment]
I have a branch with passing tests [here](https://github.com/metal/metal-uri/pull/20).

**Comment by jbalsas** [comment]
This has been merged to `develop` and is scheduled to be released in `3.0.0` tomorrow! 🤞
