### ISSUE TITLE
getParameterValues in a array containing a null element

### ISSUE THREAD

**Issue by diegonvs** [metal/metal-uri#32]
When i get an array as a parameter with a null element inside her, instead of receiving this array containing this element as of null I get type string as the example below.
<img width="1099" alt="screen shot 2017-12-29 at 16 52 10" src="https://user-images.githubusercontent.com/7663513/34447361-da43a84c-ecc1-11e7-8e59-61019f3fc52f.png">

**Comment by jbalsas** [comment]
Moved to https://github.com/metal/metal-plugins/issues/11
